Can run multiple files (serially) now.

diff --git a/orcainit4 b/orcainit4
--- a/orcainit4
+++ b/orcainit4
@@ -3,7 +3,19 @@
 orca_path=/opt/orca-4.0.1.2
 openmpi_path=/usr/local/lib/openmpi-2.0.2
 
-orca() { "${orca_path}/orca" "$1" > "$1.log"; }
+if [[! -x "${orca_path}/orca" ]]; then
+  echo "ORCA not found."
+  exit 1
+fi
+if [[! -d "${openmpi_path}/lib" ]]; then
+  echo "OpenMPI not installed."
+  exit 2
+fi
+
+orca() {
+  for file1 in "$@"; do
+    "${orca_path}/orca" "$file1" > "$file1.log"; 
+  done; }
 
 if [[ ! ${PATH} =~ ${openmpi_path} ]]; then
   export PATH="${openmpi_path}/bin":$PATH
